services:
  - type: web
    name: partner-ui
    runtime: static
    rootDir: apps/partner-ui
    buildCommand: pnpm run vercel-build
    staticPublishPath: dist
    buildFilter:
      paths:
        - apps/partner-ui/**
      ignoredPaths:
        - "**/*.test.ts"
        - "**/*.test.tsx"
        - "**/*.md"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
