import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// Autogenerated from every markdown file under apps/docs/notes/. These are the
// engineering notes / module behaviour analyses / handoffs — published so they
// are readable online alongside the curated docs.
const sidebars: SidebarsConfig = {
  notesSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
}

export default sidebars
