import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    {
      type: "autogenerated",
      dirName: "guides",
    },
  ],
  implementationSidebar: [
    {
      type: "autogenerated",
      dirName: "implementation",
    },
  ],
  referenceSidebar: [
    {
      type: "autogenerated",
      dirName: "reference",
    },
  ],
}

export default sidebars
