import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

// Autogenerated from the CURATED set of apps/docs/notes/ files allowlisted in
// docusaurus.config.ts (the `notes` plugin's `include`). Only the grounded
// module behaviour analyses are published; internal handoffs/runbooks stay private.
const sidebars: SidebarsConfig = {
  notesSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
}

export default sidebars
