/**
 * Seed: marketing-ideas-email template (#659 slice 2, PR-3)
 *
 * The single DB email template the daily tactical-ideas email relies on
 * (key: "marketing-ideas-email"). `send-ideas-email.ts` fetches it via
 * `EmailTemplatesService.getTemplateByKey`, which THROWS NOT_FOUND on a
 * missing/inactive row — so this row must exist + be active for the ideas
 * email to actually send (otherwise the send quietly skips).
 *
 * Idempotent: if a template with key "marketing-ideas-email" already exists the
 * script reports it and exits without modifying it. Delete the row (admin UI or
 * DB) to re-seed with the latest content from this file.
 *
 * Variables consumed (must stay in sync with `buildIdeasEmailTemplateData` in
 * `src/workflows/marketing/send-ideas-email-lib.ts`):
 *   - ideas_html      escaped ideas body, newlines as <br>
 *   - generated_date  the date the ideas were generated (YYYY-MM-DD)
 *   - model_used      the LLM model id
 *   - one_goal        the platform "One Goal" string
 *   - dashboard_url   optional link to the marketing dashboard
 *   - current_year    year for the footer copyright
 *
 * Run:
 *   npx medusa exec ./src/scripts/seed-marketing-ideas-email.ts
 */

import { MedusaError } from "@medusajs/framework/utils"
import { EMAIL_TEMPLATES_MODULE } from "../modules/email_templates"

const TEMPLATE_KEY = "marketing-ideas-email"

const TEMPLATE_DEFINITION = {
  name: "Daily Marketing Ideas",
  template_key: TEMPLATE_KEY,
  from: "ops@jaalyantra.com",
  subject: "Today's marketing moves — {{generated_date}}",
  html_content: `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;background:#FAFAFA;">
<div style="max-width:640px;margin:0 auto;background:#FFFFFF;border:1px solid #E4E4E7;border-radius:12px;overflow:hidden;margin-top:24px;margin-bottom:24px;">
  <div style="background:#27272A;padding:32px;text-align:center;">
    <h1 style="color:#FFFFFF;font-size:20px;font-weight:600;margin:0;">Today's marketing moves</h1>
    <p style="color:#A1A1AA;font-size:13px;margin:6px 0 0;">{{generated_date}}</p>
  </div>
  <div style="padding:32px;">
    {{#if one_goal}}<p style="color:#71717A;font-size:12px;text-transform:uppercase;letter-spacing:0.04em;margin:0 0 16px;">Goal: {{one_goal}}</p>{{/if}}
    <div style="color:#18181B;font-size:15px;line-height:1.7;">{{{ideas_html}}}</div>
    {{#if dashboard_url}}<div style="text-align:center;margin:28px 0 4px;">
      <a href="{{dashboard_url}}" style="display:inline-block;background:#27272A;color:#FFFFFF;text-decoration:none;padding:10px 24px;border-radius:8px;font-weight:500;font-size:14px;">Open the dashboard</a>
    </div>{{/if}}
  </div>
  <div style="background:#FAFAFA;padding:20px 32px;text-align:center;border-top:1px solid #E4E4E7;">
    <p style="color:#A1A1AA;font-size:10px;margin:0;">Generated by {{model_used}} · numbers verified by the hallucination guard</p>
    <p style="color:#71717A;font-size:11px;margin:6px 0 0;">&copy; {{current_year}} Jaal Yantra Textiles</p>
  </div>
</div></body></html>`,
  variables: {
    ideas_html: "Escaped ideas body (newlines as <br>)",
    generated_date: "Date the ideas were generated (YYYY-MM-DD)",
    model_used: "LLM model id used to generate the ideas",
    one_goal: "Platform 'One Goal' string",
    dashboard_url: "Optional marketing-dashboard link",
    current_year: "Current year (e.g. 2026)",
  },
  template_type: "marketing_ideas",
  is_active: true,
}

export default async function seedMarketingIdeasEmail({
  container,
}: {
  container: any
}) {
  const emailTemplatesService = container.resolve(EMAIL_TEMPLATES_MODULE)

  let existing: any = null
  try {
    existing = await emailTemplatesService.getTemplateByKey(TEMPLATE_KEY)
  } catch (err: any) {
    const isMissing =
      err instanceof MedusaError && err.type === MedusaError.Types.NOT_FOUND
    if (!isMissing) {
      console.error(
        `Failed to inspect template "${TEMPLATE_KEY}": ${err.message}`,
      )
      throw err
    }
  }

  if (existing) {
    console.log(
      `Template "${TEMPLATE_KEY}" already exists (id: ${existing.id}) — skipping.`,
    )
    console.log(
      `To re-seed with updated content, delete the row in the admin UI ` +
      `(Settings → Email Templates) and re-run this script.`,
    )
    return
  }

  console.log(`Creating email template "${TEMPLATE_KEY}"...`)
  const created = await emailTemplatesService.createEmailTemplates(
    TEMPLATE_DEFINITION,
  )
  console.log(`Created: ${TEMPLATE_DEFINITION.name} (id: ${created.id})`)
}
