import { setCartId } from "@lib/data/cookies"
import { redirect } from "next/navigation"

type Props = {
  params: Promise<{ countryCode: string; cartId: string }>
}

/**
 * Sets the provided cart ID as the active cart (cookie) and redirects
 * to the checkout page. Used for shared checkout links generated by
 * the admin design-order flow.
 */
export default async function CartCheckoutRedirect({ params }: Props) {
  const { countryCode, cartId } = await params

  if (!cartId) {
    redirect(`/${countryCode}/checkout`)
  }

  await setCartId(cartId)

  redirect(`/${countryCode}/checkout`)
}
