import {
  foldOrderCharges,
  type OrderCharge,
} from "../../modules/inventory_orders/lib/order-charges"
import { amountInWords } from "./amount-in-words"

/**
 * The PRINTABLE shape of an inventory order — what a supplier invoice says,
 * separated from how it is drawn.
 *
 * Why this exists apart from the PDF: the arithmetic on an invoice is the part
 * that can be wrong in a way nobody notices, and a pdf-lib page cannot be
 * asserted against. Everything that adds up lives here, pure and tested; the
 * renderer only positions text it is handed.
 *
 * 🔴 Charges are folded with `foldOrderCharges`, NOT re-summed here. Tax and
 * shipping RAISE what is owed, discount and adjustment LOWER it, and that sign
 * rule already has exactly one home (#1616). A second copy in a document
 * generator is how a printed invoice comes to disagree with the payable ceiling
 * the money guard enforces.
 */

export type InvoiceLineInput = {
  /** Denormalised off the line; falls back to the linked item's title. */
  material_name?: string | null
  color?: string | null
  item_title?: string | null
  sku?: string | null
  hs_code?: string | null
  unit_of_measure?: string | null
  quantity?: number | string | null
  price?: number | string | null
  /** Per-unit colour/dye job, billed on top of `price`. */
  extra_cost?: number | string | null
}

export type InvoiceRow = {
  sl: number
  description: string
  hsCode: string
  quantity: number
  unit: string
  /** What the rate column prints — "165.00+120.00" when a dye job applies. */
  rateLabel: string
  /** price + extra_cost, the number the amount is actually derived from. */
  effectiveRate: number
  amount: number
}

export type InvoiceChargeRow = {
  label: string
  amount: number
  /** false for discount/adjustment, which reduce the total. */
  raises: boolean
}

export type InventoryOrderInvoiceModel = {
  title: string
  reference: string
  orderId: string
  invoiceDate: string
  orderDate: string | null
  expectedDeliveryDate: string | null
  currencyCode: string
  supplier: {
    name: string
    taxIdLabel: string | null
    taxId: string | null
    countryCode: string | null
  }
  billTo: {
    name: string
    lines: string[]
  }
  rows: InvoiceRow[]
  totals: {
    goods: number
    charges: InvoiceChargeRow[]
    grandTotal: number
  }
  amountInWords: string
  /** Shown on the document itself — see `INVOICE_PROVENANCE_NOTE`. */
  provenanceNote: string
}

/**
 * 🔴 This document is generated by US from OUR record of the order. It is not
 * the supplier's own tax invoice and must never present itself as one: issuing
 * a tax invoice is the supplier's act, and a PDF of ours that looked like one
 * would be a document about their tax position written by their customer.
 *
 * So it is titled a PROFORMA and says where its figures came from. The partner
 * signs it and hands it back; that signature is what makes it theirs.
 */
export const INVOICE_PROVENANCE_NOTE =
  "Proforma generated by Jaal Yantra Textiles from the agreed order. Not a tax invoice. " +
  "Please verify, sign and return — or issue your own invoice if the figures differ."

const num = (value: unknown): number => {
  const parsed = Number(value ?? 0)
  return Number.isFinite(parsed) ? parsed : 0
}

const round2 = (value: number): number => Math.round(value * 100) / 100

const CHARGE_LABELS: Record<string, string> = {
  tax: "Tax",
  shipping: "Packing & Forwarding",
  discount: "Discount",
  adjustment: "Adjustment",
}

const RAISING = new Set(["tax", "shipping"])

/**
 * PURE: what one order line prints as.
 *
 * 🔑 The description folds the colour in, because two lines of the same cloth in
 * different colours are different goods and an invoice that lists "Matka" twice
 * cannot be checked against what arrived. This mirrors how the inventory items
 * themselves are named ("Matka (H.S+H.W) — Earthy Tone").
 *
 * 🔑 The rate column prints `price+extra_cost` unsummed when a dye job applies,
 * which is how the mills here write it. Printing only the total would hide the
 * one number a partner most often disputes.
 */
export const buildInvoiceRow = (
  line: InvoiceLineInput,
  index: number
): InvoiceRow => {
  const quantity = num(line.quantity)
  const price = num(line.price)
  const extra = num(line.extra_cost)
  const effectiveRate = round2(price + extra)

  const base = String(line.material_name || line.item_title || line.sku || "Item").trim()
  const color = String(line.color ?? "").trim()
  /**
   * Only append the colour when the name does not already carry it — the items
   * created through the order-line `new_material` path are titled
   * "<name> — <colour>" already, and "Matka — Red — Red" reads like a defect.
   */
  const description =
    color && !base.toLowerCase().includes(color.toLowerCase())
      ? `${base} — ${color}`
      : base

  return {
    sl: index + 1,
    description,
    hsCode: String(line.hs_code ?? "").trim(),
    quantity,
    unit: String(line.unit_of_measure || "").trim() || "Unit",
    rateLabel:
      extra > 0
        ? `${price.toFixed(2)}+${extra.toFixed(2)}`
        : price.toFixed(2),
    effectiveRate,
    amount: round2(effectiveRate * quantity),
  }
}

/**
 * PURE: fold the order, its lines and its charges into a printable invoice.
 *
 * ⚠️ `goods` is summed from the ROWS, not read off `order.total_price`. The two
 * are supposed to agree, and when they do not it is the stored total that is
 * stale — it is not recomputed on a line edit. An invoice must show what its
 * own lines add up to, or the reader can check the arithmetic and find it
 * wrong.
 */
export const buildInventoryOrderInvoiceModel = (input: {
  order: {
    id: string
    currency_code?: string | null
    order_date?: string | Date | null
    expected_delivery_date?: string | Date | null
    metadata?: Record<string, unknown> | null
  }
  lines: InvoiceLineInput[]
  charges: OrderCharge[] | null | undefined
  supplier: {
    name?: string | null
    tax_id?: string | null
    tax_id_type?: string | null
    country_code?: string | null
  } | null
  billTo: { name?: string | null; lines?: (string | null | undefined)[] }
  /** Injected so the document is reproducible in a test. */
  issuedOn?: Date
}): InventoryOrderInvoiceModel => {
  const rows = (input.lines ?? []).map(buildInvoiceRow)
  const goods = round2(rows.reduce((sum, row) => sum + row.amount, 0))

  const chargeRows: InvoiceChargeRow[] = (input.charges ?? [])
    .filter(Boolean)
    .map((charge) => {
      const type = String(charge?.type ?? "")
      return {
        label: CHARGE_LABELS[type] ?? (type ? type : "Charge"),
        amount: round2(Math.abs(num(charge?.amount))),
        raises: RAISING.has(type),
      }
    })

  const { net } = foldOrderCharges(input.charges)
  const grandTotal = round2(Math.max(0, goods + net))

  const currencyCode = String(input.order.currency_code || "inr")
  const issuedOn = input.issuedOn ?? new Date()

  const asDate = (value: string | Date | null | undefined): string | null => {
    if (!value) return null
    const d = value instanceof Date ? value : new Date(value)
    return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10)
  }

  return {
    title: "PROFORMA INVOICE",
    /**
     * The order id IS the reference. Minting an invoice number of our own would
     * create a second identifier for one document, and the partner's real
     * invoice already carries theirs.
     */
    reference: input.order.id,
    orderId: input.order.id,
    invoiceDate: issuedOn.toISOString().slice(0, 10),
    orderDate: asDate(input.order.order_date),
    expectedDeliveryDate: asDate(input.order.expected_delivery_date),
    currencyCode,
    supplier: {
      name: String(input.supplier?.name || "Supplier").trim(),
      taxIdLabel: input.supplier?.tax_id ? String(input.supplier.tax_id_type || "Tax ID") : null,
      taxId: input.supplier?.tax_id ? String(input.supplier.tax_id) : null,
      countryCode: input.supplier?.country_code ? String(input.supplier.country_code) : null,
    },
    billTo: {
      name: String(input.billTo?.name || "Jaal Yantra Textiles").trim(),
      lines: (input.billTo?.lines ?? [])
        .map((l) => String(l ?? "").trim())
        .filter(Boolean),
    },
    rows,
    totals: { goods, charges: chargeRows, grandTotal },
    amountInWords: amountInWords(grandTotal, currencyCode),
    provenanceNote: INVOICE_PROVENANCE_NOTE,
  }
}
