import { Migration } from "@medusajs/framework/mikro-orm/migrations";

// #342 — quantity_delta was integer, silently rounding decimal partial
// deliveries (1.5 kg → 2). Deliveries are in raw-material units and must
// accept decimals, matching inventory_order_line.quantity (real).
// Hand-written ALTER: the autogenerated `create table if not exists` is a
// no-op on existing databases.
export class Migration20260612202252 extends Migration {

  override async up(): Promise<void> {
    this.addSql(`alter table if exists "line_fulfillment" alter column "quantity_delta" type real using ("quantity_delta"::real);`);
  }

  override async down(): Promise<void> {
    this.addSql(`alter table if exists "line_fulfillment" alter column "quantity_delta" type integer using (round("quantity_delta")::integer);`);
  }

}
